### ISSUE TITLE
Description of the reposetory could be revised

### ISSUE THREAD

**Issue by Lxkasmehl** [Wiwaltill/HeiFa-Quiz_Web-App#3]
But only the owner can do this

**Comment by Wiwaltill** [comment]
@Lxkasmehl Do you have a suggestion?

**Comment by Lxkasmehl** [comment]
@Wiwaltill Vielleicht was ähnliches wie das hier: "A fun and interactive quiz app for Android devices that tests users' knowledge about the Heiligtumsfahrt (Pilgrimage) in Aachen, Germany."? Das ist die Beschreibung von dem Android App Repository.

**Comment by Wiwaltill** [comment]
Geändert.
